CREATE TABLE "CATEGORY" (
	"CATEGORY_ID"	INTEGER,
	"CATEGORY_NAME"	TEXT,
	"DESCRIPTION"	TEXT,
	PRIMARY KEY("CATEGORY_ID")
);

CREATE TABLE "CUSTOMER" (
	"CUSTOMER_ID"	INTEGER,
	"FIRST_NAME"	TEXT,
	"LAST_NAME"	REAL,
	"ADDRESS"	TEXT,
	"PHONE"	INTEGER,
	"EMAIL"	TEXT,
	"STAFF_ID"	INTEGER,
	PRIMARY KEY("CUSTOMER_ID"),
	FOREIGN KEY("STAFF_ID") REFERENCES "STAFF"("STAFF_ID")
);

CREATE TABLE "ORDER" (
	"ORDER_ID"	INTEGER,
	"DATE_OF_ORDER"	TEXT,
	"ORDER_DETAILS"	TEXT,
	"CUSTOMER_ID"	INTEGER,
	"SUPPLIER_ID"	INTEGER,
	PRIMARY KEY("ORDER_ID"),
	FOREIGN KEY("SUPPLIER_ID") REFERENCES "SUPPLIER"("SUPPLIER_ID")
);

CREATE TABLE "ORDER_DETAIL" (
	"ORDER_DETAIL_ID"	INTEGER,
	"UNIT_PRICE"	REAL,
	"SIZE"	BLOB,
	"QUANTITY"	INTEGER,
	"DISCOUNT"	REAL,
	"TOTAL"	REAL,
	"DATE"	TEXT,
	"PRODUCT_ID"	TEXT,
	"ORDER_ID"	INTEGER,
	"BILL_NUMBER"	INTEGER,
	PRIMARY KEY("ORDER_DETAIL_ID"),
	FOREIGN KEY("BILL_NUMBER") REFERENCES "PAYMENT"("BILL_NUMBER"),
	FOREIGN KEY("PRODUCT_ID") REFERENCES "PRODUCT"("PRODUCT_ID")
);

CREATE TABLE "PAYMENT" (
	"BILL_NUMBER"	INTEGER,
	"PAYMENT_TYPE"	TEXT,
	"OTHER_DETAILS"	TEXT,
	PRIMARY KEY("BILL_NUMBER")
);

CREATE TABLE "PRODUCT" (
	"PRODUCT_ID"	TEXT,
	"PRODUCT_NAME"	REAL,
	"PRODUCT_DESCRIPTION"	NUMERIC,
	"PRODUCT_UNIT"	TEXT,
	"PRODUCT_PRICE"	REAL,
	"PRODUCT_QUANTITY"	INTEGER,
	"PRODUCT_STATUS"	INTEGER,
	"OTHER_DETAILS"	TEXT,
	"SUPPLIER_ID"	INTEGER,
	"CATEGORY_ID"	INTEGER,
	FOREIGN KEY("CATEGORY_ID") REFERENCES "CATEGORY"("CATEGORY_ID"),
	FOREIGN KEY("SUPPLIER_ID") REFERENCES "SUPPLIER"("SUPPLIER_ID"),
	PRIMARY KEY("PRODUCT_ID")
);

CREATE TABLE "ROLE" (
	"ROLE_ID"	INTEGER,
	"ROLE_NAME"	TEXT,
	"DESCRIPTION"	TEXT,
	PRIMARY KEY("ROLE_ID")
);

CREATE TABLE "STAFF" (
	"STAFF_ID"	INTEGER,
	"FIRST_NAME"	TEXT,
	"LAST_NAME"	TEXT,
	"ADDRESS"	TEXT,
	"PHONE"	INTEGER,
	"EMAIL"	TEXT,
	"USERNAME"	TEXT,
	"PASSWORD"	TEXT,
	"ROLE_ID"	INTEGER,
	PRIMARY KEY("STAFF_ID")
);

CREATE TABLE "SUPPLIER" (
	"SUPPLIER_ID"	INTEGER,
	"NAME"	TEXT,
	"ADDRESS"	TEXT,
	"PHONE"	INTEGER,
	"EMAIL"	TEXT,
	"OTHER DETAILS"	TEXT,
	PRIMARY KEY("SUPPLIER_ID")
);